# Site settings
title: My Bad
email: shannoga@me.com
description: > # this means to ignore newlines until "baseurl:"
  This Blog is a diary of my (Mainly Objective-C and soon Swift) coding mistakes. 
baseurl: "http://shannoga.github.io" # the subpath of your site, e.g. /blog/
url: "http://shannoga.github.io" # the base hostname & protocol for your site
twitter_username: shannoga
github_username:  shannoga

# Build settings
markdown: kramdown
